services:
  node-web-app:
    image: vietanh147/node-web-app
    ports:
      - 8080:8080
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
